use_frameworks!

platform :ios, '9.0'

target 'BrainergyPrescreen_Example' do
  pod 'BrainergyPrescreen', :path => '../'

  target 'BrainergyPrescreen_Tests' do
    inherit! :search_paths

    
  end
end
